### PR TITLE
Bot load only Vehicles of the selected server

### PR DESCRIPTION
**Pull request by rewindtm**
The bot now load only the vehicles of the selected server

### CODE REVIEW

**Review by jackbayliss — CHANGES_REQUESTED** [review]
The missions won't work, for example I currently have a mission with the id
`9493012` on the UK version this does not show in the /einsaetze list meaning that unfortunately it's not a robust fix.

In terms of the vehicles I'm happy to add different json files for the countries vehicles so if you can remove all the missions and leave the vehicles code i'll be happy to review and merge.

**Comment by rewindtm** [comment]
The mission Id you have isn't the real mission id but the id associated at your account 

`https://www.missionchief.co.uk/einsaetze/12?mission_id=9537669`
`BASE_URL/einsaetze/[id]?mission_id=[id_associated_at_player]`

**Comment by jackbayliss** [comment]
> The mission Id you have isn't the real mission id but the id associated at your account
> 
> `https://www.missionchief.co.uk/einsaetze/12?mission_id=9537669`
> `BASE_URL/einsaetze/[id]?mission_id=[id_associated_at_player]`

You're correct! My bad. In that case this would be useful, but I think if the user could self generate these files it would be more useful. I'm testing the changes now.

**Comment by jackbayliss** [comment]
Moved your PR to the following branch:  https://github.com/codesidian/Python-MissionChiefBot/tree/pr/34

Will add some kind of mission generation logic, feel free to use that branch to pull / commit to with these new vehicle/mission changes.

**Pull request closed without merging**
