### PR TITLE
refactor: Changing flow

### PR DESCRIPTION
**Pull request by jackbayliss**
Additional changes to refactor flow.
Now does the following : 

1. Finds  the required vehicles and qty via the mission.
2. Tries to match the required vehicles against available vehicles.
3. Only despatches the required qty

Also includes any changes via 
https://github.com/codesidian/Python-MissionChiefBot/pull/9

(Currently only works for the fire house) - I haven't unlocked anything else. Might be a good idea to get help from the community.

### CODE REVIEW

**Comment by jackbayliss** [comment]
Handles https://github.com/codesidian/Python-MissionChiefBot/issues/10

**Comment by jackbayliss** [comment]
@piitchyy  I'm sure I can work something out.

**Comment by No-Death** [comment]
@jackbayliss If you need any help just hmu. I was thinking of like using json files as translation files so the community can make new and/or update themself. 😄

**Comment by jackbayliss** [comment]
@codesidian  Thank you, we will need to fix.

**Pull request merged**
